language: python
python:
  - "2.6"
  - "2.7"
  # - "3.2"

install: 
- pip install -r requirements.txt --use-mirrors
- pip install flexmock
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install argparse; fi

script: python setup.py test -t py.test
